# Generated by Django 5.1.5 on 2025-03-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cart_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='quantity',
        ),
    ]
