# Generated by Django 5.1.5 on 2025-03-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_order_gst_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='gst_amount',
        ),
    ]
