# Generated by Django 5.1.5 on 2025-03-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_order_gst_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
