# Generated by Django 5.1.5 on 2025-03-25 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_order_invoice_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='invoice_file_path',
            new_name='invoice_file_name',
        ),
    ]
