# Generated by Django 5.1.5 on 2025-03-11 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_color_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_images', to='products.colorvariant'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product/'),
        ),
    ]
