# Generated by Django 5.1.5 on 2025-03-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_addljlkalks_alter_sizevariant_size_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addljlkalks',
        ),
    ]
