# Generated by Django 5.1.5 on 2025-03-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_percent',
            new_name='discount_price',
        ),
    ]
