# Generated by Django 5.1.5 on 2025-03-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rrp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
