# Generated by Django 5.1.5 on 2025-03-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_rrp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rrp',
            new_name='RRP',
        ),
    ]
